/* ==========================================================================
   Confederate Provincial Authority: Chain of Command data
   Edit this file to change ranks, insignia, or dossier text.
   Insignia spec:  n = triangle count, first = 'up' | 'down', s = size scale,
                   u = [barColor, startTriangle, length]  (bar under the strip)
                   o = [barColor, startTriangle, length]  (bar over the strip)
                   hex = true adds the small Confederate hexagon
   ========================================================================== */

const BAR = { red: '#8c1118', gold: '#f5c518', cyan: '#38d6ff' };

const BRANCHES = {
  supreme: { name: 'Office of the Supreme Commander', short: 'Supreme Command', bg: '#0f1d4d', mark: '#f5b800' },
  navy:  { name: 'Confederate Navy', short: 'Navy', bg: '#3b3f63', mark: '#f5b800',
    blurb: 'The Navy is the Provincial Authority’s hidden fleet: Continuance-class battlecruisers, carrier groups and escorts built in shipyards that sit inside Osseriton’s crust and asteroid fields. It descends directly from the 9th Confederate Fleet that jumped into the Unknown Regions in 19 BBY, and its doctrine is the fleet in being: a force whose strength is known to its commanders and to no one else. Ships run on small organic crews and droid-optimized command systems, so Navy officers are trained to command alongside machines rather than over them.',
    bar: 'Crimson bar: fleet-command qualification.' },
  army:  { name: 'Confederate Army', short: 'Army', bg: '#2f4033', mark: '#9b0a0a',
    blurb: 'The Army holds the ground: the underground cities, mountain redoubts and polar caverns where Osseriton’s tens of billions live and work. Its divisions pair organic soldiers, many of them Hemes Arbora and descendants of the first CIS personnel, with droid line units from the automated foundries. Doctrine is defense in depth. If Osseriton is ever discovered, the Army’s task is to hold the surface long enough for the depths to be sealed and the fleet to leave.',
    bar: 'Gold bar: command-qualified in field exercises.' },
  intel: { name: 'CONFEDINTEL', short: 'CONFEDINTEL', bg: '#4b4c50', mark: '#1a1a78',
    blurb: 'The Confederate Intelligence Directorate runs two services under one chain of command. Internal Security watches Osseriton itself. The Veil Network, formalized by Vexis, keeps agents living ordinary lives in a hundred systems, reporting through hidden channels and never learning where their masters are. Police-style titles such as Inspector and Superintendent reflect a directorate that investigates as much as it collects. CONFEDINTEL answers to the Office of the Supreme Commander.',
    bar: 'Gold bar: Veil Network (external) service. Crimson bar: Internal Security service.' },
  droid: { name: 'Droid Command Corps', short: 'Droid Corps', bg: '#33291f', mark: '#e8832a',
    blurb: 'Five centuries of self-replicating foundries and heuristic learning cores produced a droid officer class that holds commissions of its own. The line begins with the ST-series Super Tactical Droids, whose strategic intuition descends from the neural scan of Admiral Trench, and runs down through tactical droids and command droids to the line droids that make up most of the Provincial Authority’s ground and ship complements. Droid ranks are functional designations; each droid unit is paired with an organic liaison officer by charter.',
    bar: 'Cyan bar: learning-core certified.' },
  civil: { name: 'Civil Administration', short: 'Civil', bg: '#1f4650', mark: '#dfe9f6',
    blurb: 'The Provincial Administration is the civilian half of the state described in the Provincial Charter of Confederate Continuance. Its ministries run agriculture, industry, education, justice and resource management, and the Minister President is elected by the Civilian Council, often from the Hemes Arbora constituencies. Civil authority is real in everything that is not security, but the military holds final authority whenever a security emergency is declared, which under the Permanent Emergency doctrine is never entirely over.',
    bar: 'Gold bar: Charter-confirmed office.' }
};

const COLS = ['navy', 'army', 'intel', 'droid', 'civil'];

const TIERS = [
  { c: 'SC-1', g: 'Supreme Command', d: 'Head of the armed forces' },
  { c: 'FG-3', g: 'Flag Officers', d: 'Branch and theater command' },
  { c: 'FG-2', g: 'Flag Officers', d: 'Fleet, corps and bureau command' },
  { c: 'FG-1', g: 'Flag Officers', d: 'Task force and division command' },
  { c: 'SG-3', g: 'Senior Officers', d: 'Capital ship and regiment command' },
  { c: 'SG-2', g: 'Senior Officers', d: 'Ship and battalion command' },
  { c: 'SG-1', g: 'Senior Officers', d: 'Departments and companies' },
  { c: 'JG-3', g: 'Junior Officers', d: 'Senior watch and platoon authority' },
  { c: 'JG-2', g: 'Junior Officers', d: 'Division and platoon leaders' },
  { c: 'JG-1', g: 'Junior Officers', d: 'Entry commissions and squad leaders' },
  { c: 'EG-1', g: 'Entry Grade', d: 'Cadets, recruits and trainees' }
];

const R = (t, n, i, post, text, path) => ({ t, n, i, post, text, path });

const RANKS = {
  supreme: [
    R('SC-1', 'Supreme Commander', { supreme: true },
      'Head of state; Supreme Commander of the Provincial Confederacy Armed Forces',
      'The Supreme Commander is the single apex of the Confederate chain of command and the only rank that spans both the Navy and the Army. The office has been held without interruption since 19 BBY by Vexis, an ST-series Super Tactical Droid built from the neural scan of Admiral Trench. The Supreme Commander is also Warden of the Provincial Constitution, Protector of Confederate Continuity and Senior Authority over Emergency Powers. The office holds a veto over all legislation and may dissolve the Civilian Council during a declared emergency. Vexis maintains that organic leadership fails through mortality and emotional instability, and that droid guardianship is the only reliable way to preserve the Charter.',
      'There is no promotion path. The office passes only by a Charter amendment ratified by both chambers, a procedure that has never been attempted.')
  ],
  navy: [
    R('FG-3', 'Admiral', { n: 6, first: 'up', u: ['red', 0, 5] },
      'Fleet Group command',
      'Admirals command a Fleet Group, the largest standing formation the Provincial Authority fields. Most of an Admiral’s career is spent inside the Osseriton shipyards and concealed orbital facilities rather than in open space, so the craft of the rank is patience: the readiness of every hull, the discipline of every droid command core and the silence of every emission signature. Admirals sit on the Military Senate by right.',
      'Vice Admiral to Admiral. Confirmed by the Military Senate and countersigned by the Supreme Commander.'),
    R('FG-2', 'Vice Admiral', { n: 6, first: 'up', u: ['red', 0, 3] },
      'Battle squadron command or fleet chief of staff',
      'Vice Admirals command a battle squadron of Continuance-class battlecruisers and their escorts, or serve as chief of staff to an Admiral. They are the officers most likely to lead the first squadron to leave Osseriton in the Final Phase, and they rehearse for it: every squadron exercise is run twice, once in open space and once under full emission control.',
      'Commodore to Vice Admiral. Requires a staff tour at Fleet Group headquarters.'),
    R('FG-1', 'Commodore', { n: 5, first: 'up', u: ['red', 0, 5] },
      'Task force command',
      'The Commodore is the lowest flag grade and commands a task force, a carrier-heavy group built around two or three capital ships. Commodores are the working link between an Admiral’s strategy and the captains who carry it out. The crimson bar on the plate records fleet-command qualification, earned by running a full hidden-fleet exercise without being detected by the simulated opposition’s sensors.',
      'Senior Captain to Commodore. Selected by a board of three Admirals.'),
    R('SG-3', 'Senior Captain', { n: 4, first: 'up', u: ['red', 0, 4] },
      'Capital ship command',
      'Senior Captains command Continuance-class battlecruisers, the 2,915-meter capital ships of the fleet. A battlecruiser runs on a minimal organic crew: its bridge is mostly droid officers, and its gunnery, hangar and engineering cores answer to heuristic learning systems. The skill the rank demands is not operating the ship but knowing when to overrule it.',
      'Captain to Senior Captain after commanding a cruiser or serving as battlecruiser executive officer.'),
    R('SG-2', 'Captain', { n: 4, first: 'down', u: ['red', 0, 2] },
      'Cruiser command or battlecruiser executive officer',
      'Captains command cruisers and heavy escorts, or serve as executive officer aboard a battlecruiser. The Captain is accountable for the organic crew’s welfare and for the working relationship with the ship’s droid commander, a pairing written into every vessel’s charter.',
      'Commander to Captain after a department head tour and a command qualification board.'),
    R('SG-1', 'Commander', { n: 4, first: 'up', u: ['red', 0, 2] },
      'Escort command or department head',
      'Commanders command corvettes and carrier wings, or head a ship department: Operations, Gunnery, Hangar or Engineering. On small hulls the Commander carries the entire weight of command; on large ones they carry the practical expertise that keeps the fleet running.',
      'Second Lieutenant to Commander after a full department qualification.'),
    R('JG-3', 'Second Lieutenant', { n: 3, first: 'up', u: ['red', 0, 1] },
      'Command watch authority',
      'The title means second to the Commander: the officer who holds the ship when the department heads rest. It is a senior lieutenant’s grade awarded after full watch qualification. The crimson mark under the first triangle records that the officer has stood a command watch alone.',
      'Lieutenant to Second Lieutenant after watch qualification.'),
    R('JG-2', 'Lieutenant', { n: 3, first: 'up' },
      'Division officer',
      'Lieutenants lead a division of the crew together with its attached droid units, from point-defense batteries to hangar teams. They are the first rank at which an officer writes orders rather than only carrying them out.',
      'Junior Lieutenant to Lieutenant after two years of division service.'),
    R('JG-1', 'Junior Lieutenant', { n: 2, first: 'up' },
      'Assistant division officer, starfighter or shuttle pilot',
      'Junior Lieutenants are newly commissioned. They fill assistant division posts, fly the fleet’s starfighters and shuttles, and learn how a few hundred organic officers and thousands of droids reach decisions together.',
      'Midshipman to Junior Lieutenant on graduation from the academy sea term.'),
    R('EG-1', 'Midshipman', { n: 1, first: 'up' },
      'Naval cadet',
      'Midshipmen are academy cadets embarked for their sea term. They stand supervised watches and rotate through every department, including engineering sections staffed entirely by droids. A single gold triangle is the whole insignia: the shortest line in the chain of command and the one every Admiral wore first.',
      'Entry by academy admission from the civil and military districts of Osseriton.')
  ],
  army: [
    R('FG-3', 'General', { n: 6, first: 'down', u: ['gold', 3, 3] },
      'Commanding officer of the Confederate Army',
      'The General commands the Army and answers directly to the Supreme Commander. Authority extends over every garrison in Osseriton’s mountain redoubts, polar caverns and underground cities, and over every droid division attached to them. The gold bar under the right half of the plate marks command-qualified status.',
      'Brigadier General to General. Confirmed by the Military Senate and countersigned by the Supreme Commander.'),
    R('FG-2', 'Brigadier General', { n: 6, first: 'down' },
      'Corps command',
      'Brigadier Generals command a corps, a grouping of divisions responsible for one region of Osseriton’s defense network. They write the plans that assume the unthinkable: that Osseriton has been discovered, the surface must be held, and the depths sealed behind it.',
      'Major Colonel to Brigadier General after a corps staff tour.'),
    R('FG-1', 'Major Colonel', { n: 5, first: 'down', u: ['gold', 2, 2] },
      'Division command',
      'The Major Colonel is a CIS-descended grade between Colonel and General, the commander of a division of droid and organic regiments. The gold bar beneath the middle of the plate is awarded after command of a division in the field exercises held under the sensor-masked mountain ranges.',
      'Colonel to Major Colonel. Division command is a prerequisite.'),
    R('SG-3', 'Colonel', { n: 5, first: 'down' },
      'Regiment command',
      'Colonels command regiments of mixed organic and droid battalions. They are the highest rank that still knows its soldiers by name, and Army custom keeps it that way: a Colonel reads every regimental casualty and disciplinary report personally.',
      'Major to Colonel after battalion command.'),
    R('SG-2', 'Major', { n: 5, first: 'down', u: ['gold', 3, 2] },
      'Battalion command',
      'Majors command battalions and are the senior officers most often found inside a fortified position rather than behind it. The gold bar under the right side of the plate marks a qualified battalion commander.',
      'Commander to Major after company command.'),
    R('SG-1', 'Commander', { n: 4, first: 'down' },
      'Company command',
      'In the Army a Commander leads a company, a title inherited from the CIS ground forces. Commanders direct two or three platoons plus attached droid squads and are the first rank to coordinate with other branches, calling on naval fire support or CONFEDINTEL reports.',
      'Captain to Commander after platoon and company executive service.'),
    R('JG-3', 'Captain', { n: 4, first: 'down', s: 1.12 },
      'Platoon command or company executive',
      'Captains command a reinforced platoon or serve as company executive officer. The broad triangles on the plate are a tradition kept from the early Osseriton garrisons, where a Captain’s plate had to be read at a distance in dim tunnels.',
      'Lieutenant to Captain after two years as platoon leader.'),
    R('JG-2', 'Lieutenant', { n: 3, first: 'down' },
      'Platoon leader',
      'Lieutenants lead platoons and are the first line officers with authority to commit attached droid squads independently. Most Army lieutenants are commissioned from sergeants who earned places at the academy.',
      'Sergeant to Lieutenant by academy commissioning, or directly from the academy.'),
    R('JG-1', 'Sergeant', { n: 2, first: 'down' },
      'Squad leader, first non-commissioned grade',
      'Sergeants lead a squad of organic soldiers and a team of attached droids. They are the daily face of the Army to its troops, and the grade where most of the Army’s practical knowledge is kept.',
      'Corporal to Sergeant after squad training and a leadership board.'),
    R('EG-1', 'Corporal', { n: 1, first: 'down' },
      'Fire team leader and entry grade',
      'Corporals are the Army’s entry grade, leading a fire team of soldiers and droids. A single red triangle is the whole insignia, the same triangle a Supreme Commander’s plate repeats twelve times.',
      'Entry by enlistment from any district of Osseriton.')
  ],
  intel: [
    R('FG-3', 'Director', { n: 6, first: 'down', o: ['gold', 0, 6], u: ['red', 0, 6] },
      'Director of CONFEDINTEL',
      'The Director commands both CONFEDINTEL services, Internal Security and the Veil Network, and reports to the Office of the Supreme Commander. The Director is the only person who knows the full roster of Veil agents abroad. The gold overline and crimson underline together mean the holder has served in both services.',
      'Chief Superintendent to Director by appointment of the Supreme Commander.'),
    R('FG-2', 'Chief Superintendent', { n: 6, first: 'down' },
      'Bureau chief',
      'Chief Superintendents head a bureau: Internal Security, the Veil Network, or Analysis. They own the intelligence assessments that feed the Military Senate and the Supreme Commander’s long-range planning.',
      'Superintendent to Chief Superintendent after a bureau deputy tour.'),
    R('FG-1', 'Superintendent', { n: 5, first: 'down' },
      'Division head',
      'Superintendents lead divisions inside a bureau, such as Fleet Counterintelligence or the Veil’s Outer Rim desk. They set collection priorities and approve long-term deep-cover placements.',
      'Chief Inspector to Superintendent.'),
    R('SG-3', 'Chief Inspector', { n: 4, first: 'up' },
      'Regional controller',
      'Chief Inspectors run clusters of Veil cells or Internal Security districts. By design a controller never meets the agents beneath them; reports pass through dead drops and relays, so that no one cell exposes the rest.',
      'Inspector to Chief Inspector after running a cell cluster.'),
    R('SG-2', 'Inspector', { n: 4, first: 'down' },
      'Case officer and cell controller',
      'Inspectors control individual cells or lead complex investigations on Osseriton. The title comes from the Internal Security tradition and was carried into the Veil, where an Inspector is the highest rank that still operates under cover.',
      'Captain to Inspector.'),
    R('SG-1', 'Captain', { n: 3, first: 'down' },
      'Field team leader',
      'A CONFEDINTEL Captain leads a field team of agents on a single operation, in the Veil or in Osseriton’s own districts. The rank carries authority to requisition naval transport for extraction.',
      'Sergeant to Captain.'),
    R('JG-3', 'Sergeant', { n: 3, first: 'down', s: 1.15 },
      'Senior operative and agent handler',
      'Sergeants are senior operatives who handle junior agents and informants. They are trained to keep a source alive for years, not to extract a single report.',
      'Special Agent or Agent to Sergeant by board.'),
    R('JG-2', 'Special Agent', { n: 2, first: 'down', o: ['gold', 0, 1], u: ['red', 1, 1] },
      'Agent with special authority',
      'Special Agents hold a Director’s letter of authority for a named assignment: infiltration of a warlord court, a long deep-cover placement, or a sensitive internal case. The gold overline and crimson underline on the plate record service in both the Veil and Internal Security.',
      'Agent to Special Agent by Director’s letter.'),
    R('JG-1', 'Agent', { n: 2, first: 'down' },
      'Operative',
      'Agents are fully trained operatives. Veil agents live under assumed lives among the peoples of the galaxy, as dockworkers, brokers or buyers, and report through hidden channels without ever learning where Osseriton is.',
      'Trainee Agent to Agent after a probationary posting.'),
    R('EG-1', 'Trainee Agent', { n: 1, first: 'down' },
      'Candidate',
      'Trainee Agents are candidates in a long selection course covering tradecraft, languages, cover construction and psychological resilience. Most Veil recruits are drawn from the descendants of earlier exiles who still have family in the galaxy.',
      'Entry by invitation only.')
  ],
  droid: [
    R('FG-3', 'Super Tactical Droid', { n: 6, first: 'up', o: ['cyan', 0, 6], u: ['cyan', 0, 6] },
      'Strategic command intelligence (ST-series)',
      'ST-series Super Tactical Droids are the highest droid grade and the successors to the design that produced Vexis. Their strategic intuition derives from the neural scan of Admiral Trench. They serve as strategic planners and, where the Charter allows, as commanders of whole droid formations. Supreme Commander Vexis holds the Super Tactical Droid grade in addition to the supreme office.',
      'Tactical Droid to Super Tactical Droid by Military Senate authorization, a step taken only after a learning-core audit.'),
    R('FG-2', 'Tactical Droid', { n: 5, first: 'up', u: ['cyan', 0, 5] },
      'Fleet or corps tactical command',
      'Tactical Droids plan and direct fleet or corps level operations as staff officers, running battle simulations at a speed no organic staff can match. By charter, each is paired with an organic liaison who may countermand any order that conflicts with the Charter.',
      'Strategic Command Droid to Tactical Droid after a learning-core audit.'),
    R('FG-1', 'Strategic Command Droid', { n: 5, first: 'up' },
      'Division-level command',
      'Strategic Command Droids command divisions and task forces of mixed droid and organic units. They are valued for their ability to hold a full theater picture in working memory and for never tiring during long operations.',
      'Command Droid Prime to Strategic Command Droid.'),
    R('SG-3', 'Command Droid Prime', { n: 4, first: 'up', u: ['cyan', 0, 4] },
      'Regiment or capital ship command core',
      'Command Droid Primes serve as the droid commanders of capital ships, paired with a Senior Captain, or as regimental commanders in the Army. The cyan bar marks a certified, audited learning core.',
      'Command Droid to Command Droid Prime after certification.'),
    R('SG-2', 'Command Droid', { n: 4, first: 'up' },
      'Battalion or ship department command',
      'Command Droids of the OOM line lead battalions and ship departments. They are the Corps’ main working officers, supervising line droids and reporting to organic or droid superiors.',
      'Lieutenant Droid to Command Droid.'),
    R('SG-1', 'Lieutenant Droid', { n: 3, first: 'up', u: ['cyan', 0, 3] },
      'Company command',
      'Lieutenant Droids command companies of line droids and are the first grade to carry a certified learning core, allowing independent decisions beyond the narrow protocols of the line droids beneath them.',
      'Sergeant Droid to Lieutenant Droid on core certification.'),
    R('JG-3', 'Sergeant Droid', { n: 3, first: 'up' },
      'Platoon coordination',
      'Sergeant Droids coordinate platoons of line droids and relay orders between organic officers and the units they command. They are programmed to ask for clarification rather than guess.',
      'Squad Leader Droid to Sergeant Droid.'),
    R('JG-2', 'Squad Leader Droid', { n: 2, first: 'up', u: ['cyan', 0, 2] },
      'Squad leader',
      'Squad Leader Droids lead squads of line droids and are the first grade with enough heuristic capacity to adapt a plan under fire.',
      'Elite Line Droid to Squad Leader Droid.'),
    R('JG-1', 'Elite Line Droid', { n: 2, first: 'up' },
      'Specialist line unit',
      'Elite Line Droids are upgraded line units, including commando and security droids, assigned to boarding actions, vault guard duty and sensitive facilities.',
      'Line Droid to Elite Line Droid by function upgrade.'),
    R('EG-1', 'Line Droid', { n: 1, first: 'up' },
      'Standard battle and labor droid',
      'Line Droids are the mass-produced foundation of the Provincial Authority’s labor and military strength, manufactured in the automated foundries from Osseriton’s mineral wealth. They number in the millions.',
      'Manufactured; no entry path.')
  ],
  civil: [
    R('FG-3', 'Minister President', { n: 5, first: 'up', u: ['gold', 0, 5], hex: true },
      'Head of government, Civil Administration',
      'The Minister President is elected by the Civilian Council and directs the civilian ministries. The office is currently held by a Hemes Arbora statesperson. The Minister President shapes domestic policy, resource allocation and the budget, and works alongside the Supreme Commander, who holds a legislative veto and the power to dissolve the Civilian Council during a declared emergency.',
      'Elected by the Civilian Council. No military confirmation is required for the office, but security emergencies suspend civil authority over defense matters.'),
    R('FG-2', 'Deputy Minister President', { n: 6, first: 'up' },
      'Deputy head of government',
      'The Deputy Minister President chairs the Cabinet in the Minister President’s absence and coordinates cross-ministry programs, in particular the joint planning between civilian industry and the Military Senate.',
      'Appointed by the Minister President and confirmed by the Civilian Council.'),
    R('FG-1', 'Minister', { n: 5, first: 'up', u: ['gold', 0, 5] },
      'Head of a ministry',
      'Ministers head the ministries of Agriculture, Industry, Education, Justice and Resource Continuance. The Minister of Resource Continuance controls allocation of mining, manufacturing and strategic reserves, and so holds the most influential portfolio on Osseriton.',
      'Deputy Minister to Minister by Council confirmation.'),
    R('SG-3', 'Deputy Minister', { n: 4, first: 'up', u: ['gold', 0, 4] },
      'Ministry deputy',
      'Deputy Ministers run the daily operation of a ministry and represent it before the Civilian Council. Many hold seats on both a Council committee and a joint military-civil planning board.',
      'District Prefect to Deputy Minister.'),
    R('SG-2', 'District Prefect', { n: 4, first: 'up' },
      'Governs a civilian administrative district',
      'District Prefects administer one of Osseriton’s civilian districts, including the Hemes Arbora constituencies, handling local services, justice and resource distribution. They answer to the relevant Minister and to the district’s Council members.',
      'Assistant Prefect to District Prefect.'),
    R('SG-1', 'Assistant Prefect', { n: 3, first: 'up', u: ['gold', 0, 3] },
      'Deputy district administrator',
      'Assistant Prefects manage the working departments of a district and stand in for the Prefect. They are the main point of contact between districts and the ministries.',
      'Senior Administrator to Assistant Prefect.'),
    R('JG-3', 'Senior Administrator', { n: 3, first: 'up' },
      'Section chief',
      'Senior Administrators head sections within a district or ministry: census, supply, courts, schools or agricultural zones. They hold the institutional memory of the Provincial Administration.',
      'Administrator to Senior Administrator.'),
    R('JG-2', 'Administrator', { n: 2, first: 'up', u: ['gold', 0, 2] },
      'Civil officer',
      'Administrators are full civil officers who manage cases, allocations and local programs. The gold bar marks a Charter oath taken before the Civilian Council.',
      'Junior Administrator to Administrator after the Charter oath.'),
    R('JG-1', 'Junior Administrator', { n: 2, first: 'up' },
      'Assistant civil officer',
      'Junior Administrators assist in district offices and ministry sections while completing civil service training in administration, resource law and Charter studies.',
      'Civil Cadet to Junior Administrator by examination.'),
    R('EG-1', 'Civil Cadet', { n: 1, first: 'up' },
      'Civil service entrant',
      'Civil Cadets enter the Provincial Administration from the school districts and are placed in rotating posts across ministries before choosing a specialty.',
      'Entry by civil service examination.')
  ]
};

const HISTORY = [
  { y: '22 BBY', t: 'Christophsis', d: 'Admiral Trench is gravely wounded and briefly presumed dead. Five Separatist Council members begin to doubt the Confederacy will survive the war.' },
  { y: '22 to 19 BBY', t: 'The Veiled Accord', d: 'Trench’s neural scan is used to build the first ST-series Super Tactical Droid, Vexis. The five conspirators divert wealth, warships and foundries into hidden Accord Reserves and survey the Unknown Regions for a refuge.' },
  { y: '20 BBY', t: 'Osseriton is prepared', d: 'Accord agents and Techno Union construction droids begin carving vaults, droid bays and a concealed landing field beneath a barely charted world already home to the Hemes Arbora.' },
  { y: '19 BBY', t: 'Mustafar and the jump', d: 'The Separatist Council dies. Vexis reads the shutdown order as a Republic deception, preserves the 9th Fleet’s command droids and capital ships, and jumps to Osseriton. The Treaty of Shared Sanctuary joins the exiles and the Hemes Arbora under one government.' },
  { y: '19 BBY to 5 ABY', t: 'Absolute Concealment', d: 'One world hidden is survivable; an empire is detectable. The Provincial Authority builds underground cities and hidden shipyards, and Vexis formalizes the Veil Network.' },
  { y: '5 ABY', t: 'Endor', d: 'Vexis judges that the New Republic would become another centralized tyranny. The Protocol of Continued Concealment begins.' },
  { y: '25 to 30 ABY', t: 'The Yuuzhan Vong', d: 'Total radio silence. The Veil withdraws to Osseriton, then returns to the stars once the invasion recedes.' },
  { y: '30 ABY to 500 ABY', t: 'The Great Consolidation', d: 'Self-replicating foundries, learning cores and hidden shipyards. The Continuance-class battlecruiser takes three centuries to develop.' },
  { y: '500 ABY', t: 'The Final Phase', d: 'With the central galactic government dissolved into warlord states, Vexis concludes that concealment may be ending. The Provincial Authority begins to extend order and protection to isolated worlds.' }
];
